### ISSUE TITLE
Unexpected Error - Desktop Ponies v1.63

### ISSUE THREAD

**Issue by VirusRenamon** [RoosterDragon/Desktop-Ponies#24]
`Unexpected Error - Desktop Ponies v1.63
An unexpected error occurred and Desktop Ponies must close. Please report this error so it can be fixed.
System.ComponentModel.InvalidAsynchronousStateException: An error occurred invoking the method.  The destination thread no longer exists.
   at System.Windows.Forms.Control.WaitForWaitHandle(WaitHandle waitHandle)
   at System.Windows.Forms.Control.EndInvoke(IAsyncResult asyncResult)
   at DesktopSprites.Core.ControlExtensions.CrossThreadInvoke(Control control, Action action) in _______________________________________________Desktop Ponies\Desktop Sprites\Core\ControlExtensions.cs:line 86
   at DesktopSprites.Core.ControlExtensions.TryInvoke(Control control, Action action) in _______________________________________________Desktop Ponies\Desktop Sprites\Core\ControlExtensions.cs:line 38
   at DesktopSprites.SpriteManagement.WinFormSpriteInterface.set_PreventSelfClose(Boolean value) in _______________________________________________Desktop Ponies\Desktop Sprites\SpriteManagement\WinFormSpriteInterface.cs:line 808
   at DesktopSprites.SpriteManagement.AnimationLoopBase.Run(Object startSync) in _______________________________________________Desktop Ponies\Desktop Sprites\SpriteManagement\AnimationLoopBase.cs:line 1148
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
2018-07-25 21:33:41Z`

**Comment by RoosterDragon** [comment]
Addressed via https://github.com/RoosterDragon/Desktop-Ponies/commit/1b630e26291120cd06fd40c0483c77e0cef95ccd - thanks.
